### PR TITLE
Code cleanup and NPE fix

### PR DESCRIPTION
**Pull request by mhmxs**
I did a quick review on the project and found a few things to polish.

### CODE REVIEW

**Comment by janoszen** [comment]
Hey @mhmxs thank you very much, your contributions are appreciated. I haven't put a contributor license agreement in place yet, but I'll sort it out next week and then we can merge this change. Thank you again!

**Comment by janoszen** [comment]
Hey @mhmxs the CLA bot is up, could you please sign the contributor license agreement? Then we can merge your change.

**Comment by mhmxs** [comment]
Thanks, I tried but:
"Error
There is no CLA to sign for janoszen/cscanner"

**Comment by mhmxs** [comment]
> Thanks, I tried but:
> "Error
> There is no CLA to sign for janoszen/cscanner"

it worked for second time

**Comment by janoszen** [comment]
Will merge later today, thank you.

**Comment by janoszen** [comment]
@mhmxs thank you, your PR has been merged. Please feel free to add a separate PR with your name added to the contributors list in the docs folder.

**Comment by mhmxs** [comment]
@janoszen thanks. i will, during next pr ;)

**Pull request merged**
